spring:
  profiles:
    default: dev
  application:
    name: oneclass
app:
  qr-code:
    validity-minutes: 1
server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    org.springframework: INFO

jwt:
  token-validity-in-seconds: 3600

  refresh-validity-in-seconds: 1209600   # 14Ïùº

